version: '3'

services:
  buffer-service:
    build: .
    image: buffer-service
    container_name: buffer-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY:-your_secure_key_here}
      - PORT=3000
    volumes:
      - ./logs:/usr/src/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 